# Frozen copy of the original pure-Python decoder (src/decoder.py at commit
# 8086129). It is the oracle for tests/test_decoder_equivalence.py, which checks
# that the Numba decoder reproduces it bit for bit. Do not edit this file for
# speed; if the MODEL ever changes, update both files together.
"""
M4 - Decoder and Evaluator  (the heart of the project)
======================================================
Takes a candidate solution and works out what it would actually cost.

A candidate solution is two matrices, both shape (nI, n_work_days):

  pop[i, d]  : the position of collection point i in day d's visiting order.
               Each column is a permutation of 0 .. nI-1.
  mask[i, d] : 1 if point i is collected on day d, 0 otherwise.

The decoder runs five stages:

  1. accumulate()   simulate the week, cyclically, to get w[i, t]
  2. choose_bins()  pick the cheapest workable bin combination per point
  3. build_routes() cut each day's visiting order into capacity-feasible routes
  4. time_routes()  travel time + service time + unloading time
  5. cost + penalties

Stage 1's cyclic wrap-around (Eq. 2l) is the subtle part: Monday's starting
pile depends on what was left over from Sunday, and the schedule repeats every
week, so we iterate the week until the accumulation stops changing.
"""

from __future__ import annotations

from dataclasses import dataclass, field

import numpy as np

from loader import DAY_NAMES, Instance


# ---------------------------------------------------------------------------
# Result containers
# ---------------------------------------------------------------------------
@dataclass
class Route:
    day: int
    stops: list[int]               # collection point indices, in visiting order
    loads: list[float]             # waste picked up at each stop
    cum_load: list[float]          # cumulative load after each stop
    duration: float                # minutes, depot to depot, incl. unloading

    @property
    def total_load(self) -> float:
        return self.cum_load[-1] if self.cum_load else 0.0


@dataclass
class Solution:
    instance_name: str
    bins: np.ndarray               # bins[i] = chosen bin combination for point i
    w: np.ndarray                  # w[i, t] accumulated waste, shape (nI, 7)
    wmax: np.ndarray               # wmax[i] = worst day of the week
    routes: list[Route]
    bin_cost: float
    routing_cost: float
    overall_cost: float
    feasible: bool
    penalty: float = 0.0
    violations: list[str] = field(default_factory=list)

    @property
    def fitness(self) -> float:
        """What the optimizer minimizes: true cost plus penalties."""
        return self.overall_cost + self.penalty

    def routes_on(self, day: int) -> list[Route]:
        return [r for r in self.routes if r.day == day]

    def report(self) -> str:
        lines = [f"Solution for {self.instance_name}",
                 f"  bin cost     : {self.bin_cost:8.2f} US$",
                 f"  routing cost : {self.routing_cost:8.2f} US$",
                 f"  OVERALL cost : {self.overall_cost:8.2f} US$",
                 f"  feasible     : {self.feasible}"]
        if self.violations:
            lines += [f"    ! {v}" for v in self.violations]
        lines.append("  routes:")
        for day in range(7):
            for k, r in enumerate(self.routes_on(day), start=1):
                seq = " -> ".join(["0"] + [str(s + 1) for s in r.stops] + ["0"])
                lines.append(f"    {DAY_NAMES[day]} R{k}: {seq}"
                             f"   load {r.total_load:5.2f}   {r.duration:6.2f} min")
        return "\n".join(lines)


# ---------------------------------------------------------------------------
# Stage 1 - cyclic waste accumulation  (Eqs. 2k, 2l)
# ---------------------------------------------------------------------------
def accumulate(inst: Instance, mask: np.ndarray, max_iter: int = 50) -> np.ndarray:
    """Return w[i, t] = waste sitting at point i at the END of day t.

    Waste is generated every day (including rest days) and is collected at the
    end of the day, so a visit on day t removes exactly w[i, t]. Because the
    weekly schedule repeats forever, we sweep the week repeatedly until the
    numbers settle -- that enforces the cyclic constraint Eq. (2l).
    """
    nI, n_days = inst.n_points, inst.n_days
    W = inst.W[1:]                                   # drop the depot

    # visited[i, t] over the FULL week; rest days are never collection days
    visited = np.zeros((nI, n_days), dtype=bool)
    for col, day in enumerate(inst.work_days):
        visited[:, day] = mask[:, col] == 1

    w = np.zeros((nI, n_days))
    carry = W.copy()                                 # arbitrary warm start
    for _ in range(max_iter):
        prev_carry = carry.copy()
        for t in range(n_days):
            w[:, t] = W + carry                      # today's generation + pile
            carry = np.where(visited[:, t], 0.0, w[:, t])
        if np.allclose(carry, prev_carry, atol=1e-12):
            break
    return w


# ---------------------------------------------------------------------------
# Stage 2 - bin selection  (Eqs. 2b, 2c)
# ---------------------------------------------------------------------------
def choose_bins(inst: Instance, wmax: np.ndarray, n_visits: np.ndarray) -> np.ndarray:
    """Pick, for each point, the bin combination that minimizes total weekly
    cost among those big enough to hold wmax[i].

    Important: it is NOT simply the cheapest bin that fits. A cheaper bin can
    have a longer service time, and that service time is paid on every visit
    at CCV US$/min. So the real objective per point is

        CIN_b  +  CCV * S_b * (number of visits that week)

    This is exactly what the paper's objective function (2) implies once
    service time is bin-dependent, and it is what reproduces its Appendix A
    bin choices (e.g. point 9 gets bin 4, not the cheaper-but-slower bin 3).
    """
    nI = inst.n_points
    # total weekly cost of each (point, bin) pair
    fits = inst.bin_cap[None, :] >= wmax[:, None] - 1e-9        # (nI, nB)
    cost = (inst.bin_cost[None, :]
            + inst.ccv * inst.bin_service[None, :] * n_visits[:, None])
    cost = np.where(fits, cost, np.inf)

    chosen = np.argmin(cost, axis=1)
    if not np.isfinite(cost[np.arange(nI), chosen]).all():
        raise ValueError("No bin combination is large enough for some point. "
                         "The instance needs a bigger bin or more frequent visits.")
    return chosen


# ---------------------------------------------------------------------------
# Stage 3 + 4 - route building and timing  (Eqs. 2g, 2h, 2i)
# ---------------------------------------------------------------------------
def build_day_routes(inst: Instance, day: int, order: list[int],
                     w_day: np.ndarray, bins: np.ndarray) -> list[Route]:
    """Walk the day's visiting order, filling the truck. When the next point
    would overflow the vehicle, close the route and start a new one."""
    routes: list[Route] = []
    stops: list[int] = []
    loads: list[float] = []
    cum: list[float] = []
    load = 0.0

    for i in order:
        amount = w_day[i]
        if stops and load + amount > inst.Q + 1e-9:
            routes.append(_finish(inst, day, stops, loads, cum, bins))
            stops, loads, cum, load = [], [], [], 0.0
        load += amount
        stops.append(i)
        loads.append(amount)
        cum.append(load)

    if stops:
        routes.append(_finish(inst, day, stops, loads, cum, bins))
    return routes


def _finish(inst: Instance, day: int, stops: list[int], loads: list[float],
            cum: list[float], bins: np.ndarray) -> Route:
    """Close a route and compute its duration -- Eq. (1).

    duration = sum of travel times along  0 -> s1 -> ... -> sk -> 0
             + sum of service times of the bins at each stop
             + unloading time at the depot
    Matrix indices are +1 because index 0 of C is the depot.
    """
    travel = inst.C[0, stops[0] + 1]
    for a, b in zip(stops, stops[1:]):
        travel += inst.C[a + 1, b + 1]
    travel += inst.C[stops[-1] + 1, 0]

    service = float(inst.bin_service[bins[stops]].sum())
    return Route(day=day, stops=stops, loads=loads, cum_load=cum,
                 duration=travel + service + inst.tu)


# ---------------------------------------------------------------------------
# The full decode
# ---------------------------------------------------------------------------
def decode(inst: Instance, pop: np.ndarray, mask: np.ndarray,
           lam: float = 100.0, gamma: float = 1000.0) -> Solution:
    """Evaluate a candidate solution. `lam` and `gamma` are the fleet-size and
    shift-length penalty weights of Eq. (7)."""
    nI = inst.n_points

    # --- stage 1: how much waste is where, each day -----------------------
    w = accumulate(inst, mask)
    wmax = w.max(axis=1)

    # --- stage 2: what bins to install ------------------------------------
    n_visits = mask.sum(axis=1).astype(float)
    bins = choose_bins(inst, wmax, n_visits)

    # --- stages 3 + 4: build and time the routes --------------------------
    routes: list[Route] = []
    for col, day in enumerate(inst.work_days):
        picked = np.where(mask[:, col] == 1)[0]
        if picked.size == 0:
            continue
        order = sorted(picked, key=lambda i: pop[i, col])   # follow the permutation
        routes += build_day_routes(inst, day, order, w[:, day], bins)

    # --- stage 5: cost and penalties --------------------------------------
    bin_cost = float(inst.bin_cost[bins].sum())
    total_minutes = sum(r.duration for r in routes)
    routing_cost = inst.ccv * total_minutes
    overall = bin_cost + routing_cost

    penalty, violations = 0.0, []
    for day in range(7):
        n_routes = len(([r for r in routes if r.day == day]))
        if n_routes > inst.n_vehicles:                       # Eq. (2g)
            penalty += lam * (n_routes - inst.n_vehicles) / inst.n_vehicles
            violations.append(
                f"{DAY_NAMES[day]}: {n_routes} routes > fleet of {inst.n_vehicles}")
    for r in routes:                                          # Eq. (2h)
        if r.duration > inst.TL + 1e-9:
            penalty += gamma * (r.duration - inst.TL)
            violations.append(
                f"{DAY_NAMES[r.day]}: route {r.duration:.2f} min > TL {inst.TL:.2f}")

    return Solution(
        instance_name=inst.name, bins=bins, w=w, wmax=wmax, routes=routes,
        bin_cost=bin_cost, routing_cost=routing_cost, overall_cost=overall,
        feasible=(penalty == 0.0), penalty=penalty, violations=violations,
    )


def evaluate(inst: Instance, pop: np.ndarray, mask: np.ndarray,
             lam: float = 100.0, gamma: float = 1000.0) -> float:
    """Thin wrapper returning just the fitness -- what SA and GA call."""
    return decode(inst, pop, mask, lam, gamma).fitness
